# Generated by Django 4.2.13 on 2024-05-21 02:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField()),
                ('last_name', models.CharField()),
                ('middle_name', models.CharField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Janr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, verbose_name='Название фильма')),
                ('description', models.TextField()),
                ('avatar', models.ImageField(upload_to='media/avatars')),
                ('main_artists', models.TextField()),
                ('artists', models.TextField()),
                ('created_at', models.DateField(db_index=True)),
                ('authors', models.ManyToManyField(to='cinematica.author')),
                ('janr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movies', to='cinematica.janr')),
            ],
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.TextField()),
                ('rating', models.PositiveIntegerField()),
                ('movie', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to='cinematica.movie')),
            ],
        ),
    ]
