version: '3.8'

services:
  movie_db:
    image: postgres:14
    container_name: movie_db
    restart: always
    env_file:
      - .env
    # environment:
    #   POSTGRES_USER: ${DB_ADMIN}
    #   POSTGRES_PASSWORD: ${DB_ADMIN_PASS}
    #   POSTGRES_DB: ${DB_NAME}
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - '5437:5432'
    networks:
      - movie_net


  movie:
    build: ./
    container_name: movie_container
    restart: always
    env_file:
      - .env
    volumes:
      - ./:/app
      - ./media:/app/media
    ports:
      - '8000:8000'
    depends_on:
      - movie_db
    networks:
      - movie_net

networks:
  movie_net:
    external: false